name: 🏗️ PREBUILT_A14-5.15
on:
  workflow_dispatch:

jobs:

  PREBUILT_A14_5_15_LTS:
    runs-on: ubuntu-latest
    steps:
      - name: "👨‍🔧 Setup build environment"
        run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -
      - name: "⏳ Clone Repo, Sync & Build."
        run: repo init -u https://gitlab.com/xprateek/kernel_manifest -b common-android14-5.15 --depth=1 && repo sync && tools/bazel build --config=fast //common:kernel_aarch64_dist
      - name: "📄 Generating Release Tag"
        id: tag
        run: echo "release_tag=xprateek/PREBUILT_A14-5.15-$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
      - name: "🗃️ Create Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: /home/runner/work/aosp_kernel_gki_builder/aosp_kernel_gki_builder/out/android14-5.15/dist/Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: xprateek/aosp_kernel_gki_builder
          TOKEN: ${{ secrets.TOKEN }}

  PREBUILT_A14_5_15_LTS_KSU:
    runs-on: ubuntu-latest
    steps:
      - name: "👨‍🔧 Setup build environment"
        run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -
      - name: "⏳ Clone Repo, Sync & Build."
        run: repo init -u https://gitlab.com/xprateek/kernel_manifest -b common-android14-5.15 --depth=1 && repo sync && cd common && curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash - && cd ../ && tools/bazel build --config=fast //common:kernel_aarch64_dist
      - name: "📄 Generating Release Tag"
        id: tag
        run: echo "release_tag=xprateek/PREBUILT_A14-5.15_KSU-$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
      - name: "🗃️ Create Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: /home/runner/work/aosp_kernel_gki_builder/aosp_kernel_gki_builder/out/android14-5.15/dist/Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: xprateek/aosp_kernel_gki_builder
          TOKEN: ${{ secrets.TOKEN }}
